.TH "Project5/Origem.cpp" 3 "Thu May 17 2018" "Version 1.0" "Shilton_RLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Project5/Origem.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <complex>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Classes_cirkt\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 7 of file Origem\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Shilton_RLC from the source code\&.
