.TH "Resistor" 3 "Thu May 17 2018" "Version 1.0" "Shilton_RLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Resistor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Classes_cirkt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResistor\fP (float valor)"
.br
.ti -1c
.RI "void \fBset_imp\fP (float w)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Classes_cirkt\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Resistor::Resistor (float valor)"

.PP
Definition at line 12 of file Classes_cirkt\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Resistor::set_imp (float w)"

.PP
Definition at line 15 of file Classes_cirkt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Shilton_RLC from the source code\&.
